version: "3.7"

services:
  C:
    image: vincentserpoul/paritypoa:v2.5.0
    ports:
      - "8549:8549"
      - "8550:8550"
      - "30305:30305"
    environment:
      - JSONRPC_PORT=8549
      - WS_PORT=8550
      - NETWORK_PORT=30305
    volumes:
      - chain_C:/home/parity/.local/share/io.parity.ethereum
    configs:
      - source: PoA.json
        target: /home/parity/.poaconfigs/PoA.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: configPoANode.C.toml
        target: /home/parity/.poaconfigs/configPoANode.toml
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.C.address
        target: /home/parity/.poaconfigs/authority.address
        uid: "1000"
        gid: "1000"
        mode: 0400
    secrets:
      - source: authority.C.priv.json
        target: /home/parity/.poasecrets/authority.priv.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.C.password
        target: /home/parity/.poasecrets/authority.password
        uid: "1000"
        gid: "1000"
        mode: 0400
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=C]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chain_C:
    driver_opts:
      o: rw

configs:
  PoA.json:
    external: true
  configPoANode.C.toml:
    external: true
  authority.C.address:
    external: true

secrets:
  authority.C.priv.json:
    external: true
  authority.C.password:
    external: true
